import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy · AI Interview Practice',
  description: 'How AI Interview Practice collects, uses, and protects your data.',
};

export default function PrivacyPage() {
  return (
    <div className="legal-root">
      <header className="legal-header">
        <Link href="/" className="legal-back">← AI Interview Practice</Link>
      </header>

      <main className="legal-body">
        <h1>Privacy Policy</h1>
        <p className="legal-updated">Last updated: July 2026</p>

        <p>
          This policy explains what data AI Interview Practice (the &quot;Service&quot;)
          collects, how it is used, and the choices you have. The short version: we
          collect what is needed to run a practice platform with AI coaching, we do not
          sell your data, and we do not run advertising trackers.
        </p>

        <h2>1. Data We Collect</h2>
        <ul>
          <li>
            <strong>Account data.</strong> Your email address and authentication
            credentials, managed by our authentication provider (Supabase). Passwords
            are stored hashed; we never see them in plain text.
          </li>
          <li>
            <strong>Practice activity.</strong> The code you write in scenarios, test
            results, messages you exchange with the AI coach, session events (such as
            when you run tests or view an answer key), and the AI-generated scores and
            feedback for your sessions. This history powers your review and progress
            screens.
          </li>
          <li>
            <strong>Payment data.</strong> Payments are processed by Stripe. We receive
            your subscription status and billing events; we never receive or store your
            card number.
          </li>
          <li>
            <strong>Technical data.</strong> Standard server logs (IP address, browser
            type, timestamps) generated by operating and securing the Service.
          </li>
        </ul>

        <h2>2. How We Use Data</h2>
        <ul>
          <li>To provide the Service: run scenarios, save your sessions, show your history and scores.</li>
          <li>To power AI features: your code, session context, and chat messages are sent to Anthropic (our AI provider) to generate coaching responses and performance feedback.</li>
          <li>To manage billing, plan limits, and prevent abuse (such as rate limiting).</li>
          <li>To communicate with you about your account (confirmation emails, password resets).</li>
        </ul>
        <p>We do not sell your personal data or share it with advertisers.</p>

        <h2>3. AI Processing</h2>
        <p>
          When you use AI coaching or end a session, relevant content (your code, the
          scenario context, your chat messages, and session activity metrics) is sent to
          Anthropic&apos;s API to generate responses and feedback. Under Anthropic&apos;s
          commercial API terms, API inputs and outputs are not used to train their
          models by default. Avoid pasting sensitive personal information into the
          editor or chat; it is not needed for any scenario.
        </p>

        <h2>4. Service Providers</h2>
        <p>We share data only with the processors needed to run the Service:</p>
        <ul>
          <li><strong>Supabase</strong>: authentication and database hosting (account data, session history).</li>
          <li><strong>Stripe</strong>: payment processing and subscription management.</li>
          <li><strong>Anthropic</strong>: AI coaching and grading (session content, as described above).</li>
          <li><strong>Hosting provider</strong> (e.g., Vercel): serving the application and standard request logs.</li>
        </ul>

        <h2>5. Cookies and Local Storage</h2>
        <p>
          We use authentication cookies (via Supabase) to keep you signed in, and
          browser local storage for product preferences such as onboarding state. We do
          not use third-party advertising or analytics trackers.
        </p>

        <h2>6. Data Retention and Deletion</h2>
        <p>
          Account and session data are retained while your account is active. You can
          request deletion of your account and associated data at any time by emailing{' '}
          <a href="mailto:divjotmuchhal@gmail.com">divjotmuchhal@gmail.com</a> from your
          account email; we will delete it within 30 days, except where retention is
          required for legal or billing-record purposes.
        </p>

        <h2>7. Your Rights</h2>
        <p>
          Depending on where you live (for example, the EU/EEA under GDPR or California
          under CCPA), you may have rights to access, correct, export, or delete your
          personal data, and to object to certain processing. To exercise any of these
          rights, contact us at the email below. We do not discriminate against you for
          exercising them.
        </p>

        <h2>8. Security</h2>
        <p>
          Data is transmitted over HTTPS and stored with access controls via our
          providers. No method of transmission or storage is completely secure; we
          cannot guarantee absolute security, but we take reasonable measures
          appropriate to the data we hold.
        </p>

        <h2>9. Children</h2>
        <p>
          The Service is not directed to children under 13, and we do not knowingly
          collect data from them. If you believe a child has provided us data, contact
          us and we will delete it.
        </p>

        <h2>10. Changes to This Policy</h2>
        <p>
          We may update this policy as the Service evolves. Material changes will be
          communicated through the Service or by email. The &quot;Last updated&quot; date above
          reflects the current version.
        </p>

        <h2>11. Contact</h2>
        <p>
          Privacy questions or requests:{' '}
          <a href="mailto:divjotmuchhal@gmail.com">divjotmuchhal@gmail.com</a>
        </p>
      </main>

      <footer className="legal-footer">
        <Link href="/terms">Terms</Link>
        <span aria-hidden="true">·</span>
        <Link href="/privacy">Privacy</Link>
        <span aria-hidden="true">·</span>
        <Link href="/">Home</Link>
      </footer>
    </div>
  );
}
